version: '3'

services:
   GoLang:
      container_name: GoLang
      image: golang:1.17
      # コンテナのusr/srcフォルダをマウント
      volumes:
         - ./src:/usr/src
      working_dir: /usr/src
      tty: true
   
   # Front側用
   webapp:
      container_name: WebApp
      build: ./front
      ports:
        - "8080:80"
      volumes:
        - ./front/gatch_game/build/web:/usr/local/apache2/htdocs httpd 
      tty: true


